[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -O2
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

upload_speed = 115200
upload_port = COM3 

board_build.partitions = huge_app.csv
